var testdata = [
	{ 
		id: "1",
		title: "Breaking bad",
		start: "2014-09-16T20:57:00Z",
		end: "2014-09-16T21:57:00Z",
		genre: "Action",
		language: "English",
		subtitles: "Dutch",
		rating: "12",
		short_sysnopsis: "Breaking Bad is the story of Walter White, a struggling high school chemistry teacher who is diagnosed with inoperable lung cancer at the beginning of the series. He turns to a life of crime, producing and selling methamphetamine, in order to secure his family's financial future before he dies.", 
		sysnopsis: "Breaking Bad is an American crime drama television series created and produced by Vince Gilligan. Set and produced in Albuquerque, New Mexico, Breaking Bad is the story of Walter White, a struggling high school chemistry teacher who is diagnosed with inoperable lung cancer at the beginning of the series. He turns to a life of crime, producing and selling methamphetamine, in order to secure his family's financial future before he dies, teaming with his former student, Jesse Pinkman. Heavily serialized, the series is known for positioning its characters in seemingly inextricable corners and has been labeled a contemporary western by its creator.",
		cast: "Bryan Cranston, Anna Gunn, Aaron Paul, Dean Norris",
		poster: "https://image.tmdb.org/t/p/w396/4yMXf3DW6oCL0lVPZaZM2GypgwE.jpg",
		large_image: "https://image.tmdb.org/t/p/w780/bzoZjhbpriBT2N5kwgK0weUfVOX.jpg",
		channel_logo: "http://staticfiles.rtl.nl/styles/img/logos/logo_rtl5.png"
	},
	{ 
		id: "2",
		title: "The Good Wife",
		start: "2014-09-16T21:57:00Z",
		end: "2014-09-16T22:57:00Z",
		genre: "Drama",
		language: "English",
		subtitles: "Dutch",
		rating: "ALL",
		short_sysnopsis: "The Good Wife is a legal drama starring Emmy Award winner Julianna Margulies as a wife and mother who boldly assumes full responsibility for her family and re-enters the workforce after her husband's very public sex and political corruption scandal lands him in jail.", 
		sysnopsis: "Alicia has been a good wife to her husband, a former state's attorney. After a very humiliating sex and corruption scandal, he is behind bars. She must now provide for her family and returns to work as a litigator in a law firm.",
		cast: "Julianna Margulies, Josh Charles, Christine Baranski, Matt Czuchry, Archie Panjabi",
		poster: "https://image.tmdb.org/t/p/w396/7mUIQ2a4dlCjibD897pDc92qWQ7.jpg",
		large_image: "https://image.tmdb.org/t/p/w780/orUHAWxpH0AK2dthKkWPiMZEeJ4.jpg",
		channel_logo: "http://staticfiles.rtl.nl/styles/img/logos/logo_rtl7_trans.png"
	},{ 
		id: "3",
		title: "Yukon Gold",
		start: "2014-09-17T15:00:00Z",
		end: "2014-09-17T16:00:00Z",
		genre: "Reality-TV",
		language: "English",
		subtitles: "Dutch",
		rating: "12",
		short_sysnopsis: "The series follows four mining crews as they search for gold over the four month Yukon mining season.", 
		sysnopsis: "Yukon Gold is a Canadian reality television series produced by Paperny Entertainment that airs on History Television. The series follows four mining crews as they search for gold over the four month Yukon mining season. Miners Ken Foy, Al McGregor, Bernie Kreft and Karl Knutson each head one of the crews. The series has been acquired in the United States by National Geographic Channel and will air in 2013.",
		cast: "",
		poster: "http://vod.cdn.eastlink.ca/CDN/images/YukonGold_YukonGoldS1_YukonGoldS1E1010_boxart.jpg",
		large_image: "http://wpmedia.o.canada.com/2013/03/yukon-gold-miners.jpg",
		channel_logo: "http://ftlob.nl/wp-content/uploads/logo-NatGeo.jpg"
	},{ 
		id: "4",
		title: "Outlander",
		start: "2014-09-16T15:00:00Z",
		end: "2014-09-16T16:00:00Z",
		genre: "Action",
		language: "English",
		subtitles: "Dutch",
		rating: "ALL",
		short_sysnopsis: "Outlander follows the story of Claire Randall, a married combat nurse from 1945 who is mysteriously swept back in time to 1743, where she is immediately thrown into an unknown world where her life is threatened", 
		sysnopsis: "Outlander follows the story of Claire Randall, a married combat nurse from 1945 who is mysteriously swept back in time to 1743, where she is immediately thrown into an unknown world where her life is threatened. When she is forced to marry Jamie, a chivalrous and romantic young Scottish warrior, a passionate affair is ignited that tears Claire's heart between two vastly different men in two irreconcilable lives. The Outlander series, adapted from Diana Gabaldon's international best-selling books, spans the genres of romance, science-fiction, history and adventure into one epic tale. From Executive Producer Ronald D. Moore. The series is set to premiere on STARZ August 9 in the US.",
		cast: "Caitriona Balfe, Sam Heughan, Gary Lewis, Tobias Menzies, Graham McTavish",
		poster: "https://image.tmdb.org/t/p/w396/6EdnG97lo3SOu3WmSQ2SmiHG8jo.jpg",
		large_image: "https://image.tmdb.org/t/p/w780/I7P6pld2uk3KwEt2o2ju7yyQ3n.jpg",
		channel_logo: "http://upload.wikimedia.org/wikipedia/commons/thumb/d/de/HBO_logo.svg/422px-HBO_logo.svg.png"
	},{ 
		id: "5",
		title: "Game of Thrones",
		start: "2014-09-19T18:05:00Z",
		end: "2014-09-19T19:05:00Z",
		genre: "Sci-Fi & Fantasy, Drama",
		language: "English",
		subtitles: "Dutch",
		rating: "12",
		short_sysnopsis: "The series, set on the fictional continents of Westeros and Essos at the end of a decade-long summer, interweaves several plot lines.", 
		sysnopsis: "Game of Thrones is an American fantasy drama television series created for HBO by David Benioff and D. B. Weiss. It is an adaptation of A Song of Ice and Fire, George R. R. Martin's series of fantasy novels, the first of which is titled A Game of Thrones. The series, set on the fictional continents of Westeros and Essos at the end of a decade-long summer, interweaves several plot lines. The first follows the members of several noble houses in a civil war for the Iron Throne of the Seven Kingdoms; the second covers the rising threat of the impending winter and the mythical creatures of the North; the third chronicles the attempts of the exiled last scion of the realm's deposed dynasty to reclaim the throne. Through its morally ambiguous characters, the series explores the issues of social hierarchy, religion, loyalty, corruption, sexuality, civil war, crime, and punishment.",
		cast: "Peter Dinklage, Nikolaj Coster-Waldau, Lena Headey, Emilia Clarke, Kit Harington",
		poster: "https://image.tmdb.org/t/p/w396/pVC9o9LLnhuPpas0B0p9spqAxNg.jpg",
		large_image: "https://image.tmdb.org/t/p/w780/y3iZibhyEmFCrdRENGaSZHM2fSm.jpg",
		channel_logo: "http://upload.wikimedia.org/wikipedia/commons/thumb/d/de/HBO_logo.svg/422px-HBO_logo.svg.png"
	},{ 
		id: "6",
		title: "Manhattan",
		start: "2014-09-16T20:57:00Z",
		end: "2014-09-16T21:57:00Z",
		genre: "Drama",
		language: "English",
		subtitles: "Dutch",
		rating: "12",
		short_sysnopsis: "Breaking Bad is the story of Walter White, a struggling high school chemistry teacher who is diagnosed with inoperable lung cancer at the beginning of the series. He turns to a life of crime, producing and selling methamphetamine, in order to secure his family's financial future before he dies.", 
		sysnopsis: "Set against the backdrop of the greatest clandestine race against time in the history of science with the mission to build the world's first atomic bomb in Los Alamos, New Mexico. Flawed scientists and their families attempt to co-exist in a world where secrets and lies infiltrate every aspect of their lives.",
		cast: "John Benjamin Hickey, Olivia Williams, Ashley Zukerman, Rachel Brosnahan, Daniel Stern",
		poster: "https://image.tmdb.org/t/p/w396/8OIMO7apF8Jhx54vvYxrbK3wQvI.jpg",
		large_image: "https://image.tmdb.org/t/p/w780/5Z3LQHTPYK0kNBwURQTjQomv8Go.jpg",
		channel_logo: "http://staticfiles.rtl.nl/styles/img/logos/logo_rtl7_trans.png"
	}
];